spring.application.name=boost-mood-bot

spring.config.import=optional:file:./config/common/application.properties,\
                      optional:file:./config/database/application.properties,\
                      optional:file:./config/logs/application.properties,\
                      optional:file:./config/telegram/application.properties,\
                      optional:file:./config/z_override/application.properties
spring.profiles.active=test